package entidades;
// Generated 02-06-2021 12:09:57 by Hibernate Tools 4.3.1



/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private Integer id;
     private Producto producto;
     private String descripcion;

    public Log() {
    }

	
    public Log(Producto producto) {
        this.producto = producto;
    }
    public Log(Producto producto, String descripcion) {
       this.producto = producto;
       this.descripcion = descripcion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


