package entidades;
// Generated 02-06-2021 12:09:57 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer numdoc;
     private Date fecha;
     private Set detalleVentas = new HashSet(0);

    public Venta() {
    }

	
    public Venta(Date fecha) {
        this.fecha = fecha;
    }
    public Venta(Date fecha, Set detalleVentas) {
       this.fecha = fecha;
       this.detalleVentas = detalleVentas;
    }
   
    public Integer getNumdoc() {
        return this.numdoc;
    }
    
    public void setNumdoc(Integer numdoc) {
        this.numdoc = numdoc;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set detalleVentas) {
        this.detalleVentas = detalleVentas;
    }
    public int getId() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }





}


